Website = "https://github.com/r0b0/mpd-radio"

[Details]
  Icon = "Icon.png"
  Name = "MPD Radio"
  ID = "sk.hq.r0b0.mpdradio"
  Version = "24.09"
  Build = 1

[LinuxAndBSD]
  Categories = ["AudioVideo"]
  Comment = "Listen to inernet radios using MPD servers"
