# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push, pull_request]
  

jobs:

  build-linux-x86-64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential libgl1-mesa-dev xorg-dev
        version: 1.0

    - name: Build
      run: go build -ldflags "-s -w" -v ./...
      
    - name: Production artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86-64
        path: mpd_radio


  build-windows-x86-64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build -ldflags "-s -w" -v ./...
      
    - name: Production artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-x86-64
        path: mpd_radio.exe
        
        
  build-macos-x86-64:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build -ldflags "-s -w" -v ./...
      
    - name: Production artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-x86-64
        path: mpd_radio
        

  build-macos-arm64:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build -ldflags "-s -w" -v ./...
      
    - name: Production artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64
        path: mpd_radio
